<a href="https://colab.research.google.com/github/albertaillet/Miniproject1/blob/master/Deep_Q-Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

If using the notebook on [Colab](https://colab.research.google.com/), run this cell to get the correct files downloaded.

In [1]:
import os
if "Miniproject1" not in os.getcwd():
  !git clone https://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@github.com/albertaillet/Miniproject1/
  %cd Miniproject1/
%ls

fatal: destination path 'Miniproject1' already exists and is not an empty directory.
/content/Miniproject1
Deep_Q-Learning.ipynb  performance_measures.py  README.md   tic_plot.py
images/                __pycache__/             runs/       tic_tac_toe.ipynb
MP_TicTocToe.pdf       Q-learning.ipynb         tic_env.py


In [2]:
%load_ext tensorboard

In [3]:
import random
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from pytz import timezone
from IPython.display import clear_output
from collections import namedtuple, deque
from tic_env import TictactoeEnv, OptimalPlayer
timezone_cet = timezone("CET")

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision.transforms as T
from torch.utils.tensorboard import SummaryWriter

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

## 3. Deep Q-Learning

As our 2nd algorithm, we use Deep Q-Learning (DQN) combined with $\epsilon$-greedy policy. You can watch again Part 1 of Deep Reinforcement Learning Lecture 1 for an introduction to DQN and Part 1 of Deep Reinforcement Learning Lecture 2 (in particular slide 8) for more details. The idea in DQN is to approximate $Q$-values by a neural network instead of a look-up table as in Tabular Q-learning. For implementation, you can use ideas from the DQN tutorials of [Keras](https://keras.io/examples/rl/deep_q_network_breakout/) and [PyTorch](https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html).

### 3.1 Implementation details
State representation: We represent state $s_{t}$ by a $3 \times 3 \times 2$ tensor `x_t`. Each element of `x_t` takes a value of 0 or 1. The $3 \times 3$ matrix `x_t[:,:,0]` shows positions taken by you, and `x_t[:,:,1]` shows positions taken by your opponent. If `x_t[i, j, 0]=x_t[i, j, 1]=0`, then position $(i, j)$ is available.
Neural network architecture: We use a fully connected network. State `x_t` is fed to the network at the input layer. We consider 2 hidden layers each with 128 neurons - with ReLu activation functions. The output layer has 9 neurons (for 9 different actions) with linear activation functions. Each neuron at the output layer shows the $Q$-value of the corresponding action at state `x_t`.

Unavailable actions: For DQN, we do not constraint actions to only available actions. However, whenever the agent takes an unavailable action, we end the game and give the agent a negative reward of value $r_{\text {unav }}=-1$.

Free parameters: DQN has many hyper parameters. For convenience, we fix the discount factor at $\gamma=0.99$. We assume a buffer size of $10^{\prime} 000$ and a batch size of 64 . We update the target network every 500 games. Instead of squared loss, we use the Huber loss (with $\delta=1$ ) with Adam optimizer (c.f. the DQN tutorials of Keras and PyTorch). You can fine tune the learning rate if needed, but we suggest $5 \times 10^{-4}$ as a starting point.

Other options? There are tens of different ways to make training of deep networks more efficient. Do you feel like trying some and learning more? You are welcome to do so; you just need to explain the main features of your implementation and a brief summary of your reasoning in less than 300 words under the title 'Implementation details' in your report.

In [4]:
#@title Parameters

HIDDEN_SIZE = 128 #@param {type:"integer"}
GAMMA = 0.99  #@param {type:"number"}
ALPHA = 5e-4  #@param {type:"number"}
BUFFER_SIZE = 10000 #@param {type:"integer"}
BATCH_SIZE = 64 #@param {type:"integer"}
LOG_EVERY = 250 #@param {type:"integer"}
UPDATE_EVERY = 500 #@param {type:"integer"}

In [5]:
class DQN(nn.Module):

    def __init__(self, input_size=18, hidden_size=128, output_size=9):
        super().__init__()
        self.seq = nn.Sequential(
            nn.Flatten(),
            nn.Linear(input_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, output_size)
        ).to(device)

    def forward(self, x):
        x = x.to(device)
        x = x.view(-1, 3, 3, 2)
        return self.seq(x)

The following cell creates a class for the replay buffer and uses code from [Replay Memory](https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html#replay-memory)

In [6]:
Transition = namedtuple('Transition', ('state', 'action', 'next_state', 'reward', 'player'))

class ReplayBuffer(object):

    def __init__(self, buffer_size, batch_size):
        self.buffer = deque([], maxlen=buffer_size)
        self.batch_size = batch_size

    def push(self, *args):
        """Save a transition"""
        self.buffer.append(Transition(*args))

    def get_batch(self, batch_size=None):
        if batch_size is None:
          batch_size = self.batch_size
        return random.sample(self.buffer, batch_size)

    def __len__(self):
        return len(self.buffer)

    def has_one_batch(self, batch_size=None):
        if batch_size is None:
          batch_size = self.batch_size
        return len(self) >= batch_size

The following cell creates a function to call to optimize the model and uses code from 
[Training loop](https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html#training-loop)

In [7]:
p2v = {'X': 1, 'O': -1}

In [8]:
def state_to_tensor(state, player):
  if player==-1:
    opponent_player = 1
  elif player==1:
    opponent_player = -1
  elif p2v[player]==-1:
    player = p2v[player]
    opponent_player = 1
  elif p2v[player]==1:
    player = p2v[player]
    opponent_player = -1
  else:
    raise ValueError(f"Player should be 1 or -1, player={player}")

  t = np.zeros((3, 3, 2), dtype=np.float32)
  t[:, :, 0] = (state == player)
  t[:, :, 1] = (state == opponent_player)
  return torch.tensor(t, dtype=torch.float32, device=device)

In [9]:
class DeepEpsilonGreedy:
    def __init__(self, epsilon=0, n_actions=9):
        self.epsilon = epsilon
        self.n_actions = n_actions
        self.player = None
    
    def set_epsilon(self, epsilon):
        self.epsilon = epsilon

    def set_player(self, player):
        self.player = player
    
    def act(self, state):
      if np.random.random() > self.epsilon:
          state = state_to_tensor(state, self.player)
          with torch.no_grad():
              return Q1(state).max(1).indices.item()
      else:
          return random.randrange(self.n_actions)

In [10]:
def optimize_model(Q1: nn.Module, 
                   Q2: nn.Module, 
                   buffer: ReplayBuffer, 
                   optimizer: optim.Optimizer):
    if not buffer.has_one_batch():
        return
    transitions = buffer.get_batch()
    batch = Transition(*zip(*transitions))

    state_batch = torch.stack([state_to_tensor(s, p) for s, p in zip(batch.state, batch.player)])
    action_batch = torch.tensor(batch.action, device=device)
    reward_batch = torch.tensor(batch.reward, device=device)
    non_final_mask = torch.tensor(tuple(map(lambda s: s is not None,
                                          batch.next_state)), device=device, dtype=torch.bool)
    if non_final_mask.sum().item() > 0:
      non_final_next_states = torch.stack([state_to_tensor(s, p) for s, p in zip(batch.next_state, batch.player)
                                                  if s is not None])
    
    # See slide 13 Lecture 10

    # Compute Q1(s, a)
    state_action_values = Q1(state_batch).take(action_batch)

    # Compute max_a' Q2(s', a'), it is set to 0 when the state is final
    next_state_values = torch.zeros(action_batch.size()[0], device=device)
    if non_final_mask.sum().item() > 0:
      next_state_values[non_final_mask] =  Q2(non_final_next_states).max(1).values.detach()

    # Compute the expected Q values: (r + gamma * max_a' Q2(s', a'))
    expected_state_action_values = reward_batch + (GAMMA * next_state_values)

    # Compute Huber loss
    criterion = nn.HuberLoss(delta=1.0)
    loss = criterion(state_action_values, expected_state_action_values)
    loss_val = loss.item()

    # Optimize the model
    optimizer.zero_grad()
    loss.backward()
    for param in Q1.parameters():
        param.grad.data.clamp_(-1, 1)
    optimizer.step()
    return loss_val

### Question 11

Plot average reward and average training loss for every 250 games during training. Does the loss decrease? Does the agent learn to play Tic Tac Toe?

In [11]:
epsilon = 0.5
epsilon_opt = 0.5

env = TictactoeEnv()
buffer = ReplayBuffer(BUFFER_SIZE, BATCH_SIZE)
Q1 = DQN(hidden_size=HIDDEN_SIZE)
Q2 = DQN(hidden_size=HIDDEN_SIZE)
Q2.load_state_dict(Q1.state_dict())
optimizer = optim.Adam(Q1.parameters())
policy = DeepEpsilonGreedy(epsilon=epsilon, n_actions=9)
date = datetime.now(timezone_cet).strftime("%b%d_%H-%M")
writer = SummaryWriter(log_dir=f"runs/{date} Epsilon: {epsilon}, Epsilon opt: {epsilon_opt}, Batch Size: {BATCH_SIZE}, Buffer Size: {BUFFER_SIZE}")

In [12]:
num_trained_games = 0
av_rewards = []
av_loss = []

In [13]:
num_games = 20000
opponent_player = OptimalPlayer(epsilon_opt, player='O')
policy.set_player('X')
rewards = []
losses = []
n_unavilable_actions_taken = 0

for itr in range(num_games):
    env.reset()
    state, end, _ = env.observe()

    opponent_player.player, policy.player = policy.player, opponent_player.player

    if opponent_player.player == 'X':
        opponent_move = opponent_player.act(state)
        state, end, _ = env.step(opponent_move)

    while not end:
        move = policy.act(state)
        valid_move = env.check_valid(move)
        
        if valid_move:
          next_state, end, _ = env.step(move)

        if valid_move and (not end) and (env.current_player == opponent_player.player):
          opponent_move = opponent_player.act(next_state)
          next_state, end, _ = env.step(opponent_move)
          reward = env.reward(player=policy.player)
          buffer.push(state, move, next_state, reward, policy.player)
        elif valid_move and end:
          reward = env.reward(player=policy.player)
          buffer.push(state, move, None, reward, policy.player)        
        elif not valid_move:
          end = True
          reward = -1
          n_unavilable_actions_taken += 1
          buffer.push(state, move, None, reward, policy.player)
          break
        else:
          raise ValueError("invalid move")

        loss = optimize_model(Q1, Q2, buffer, optimizer)
        
        if loss is not None:
          losses.append(loss)
        
        state = next_state.copy()

    rewards.append(reward)
    
    if len(rewards) >= LOG_EVERY:
        writer.add_scalar("Average Reward", np.mean(rewards), itr)
        writer.add_scalar("Average Loss", np.mean(loss), itr)
        writer.add_scalar("Number of unavilable actions taken", n_unavilable_actions_taken, itr)
        writer.flush()
        rewards = []
        losses = []
        n_unavilable_actions_taken = 0

    if (itr) % UPDATE_EVERY == 0:
      Q2.load_state_dict(Q1.state_dict())      
    num_trained_games += 1
    env.reset()
writer.flush()

In [ ]:
%tensorboard --logdir=runs

### Question 12

Repeat the training but without the replay buffer and with a batch size of 1 : At every step, update the network by using only the latest transition. What do you observe?

In [ ]:
epsilon = 0.5
epsilon_opt = 0.5

env = TictactoeEnv()
buffer = ReplayBuffer(1, 1)
Q1 = DQN(hidden_size=HIDDEN_SIZE)
Q2 = DQN(hidden_size=HIDDEN_SIZE)
Q2.load_state_dict(Q1.state_dict())
optimizer = optim.Adam(Q1.parameters())
policy = DeepEpsilonGreedy(epsilon=epsilon, n_actions=9)
date = datetime.now(timezone_cet).strftime("%b%d_%H-%M")
writer = SummaryWriter(log_dir=f"runs/{date} Epsilon: {epsilon}, Epsilon opt: {epsilon_opt}, Batch Size: {1}, Buffer Size: {1}")

In [ ]:
num_trained_games = 0
av_rewards = []
av_loss = []

In [ ]:
num_games = 20000
opponent_player = OptimalPlayer(epsilon_opt, player='O')
learning_player = 'X'
rewards = []
losses = []
n_unavilable_actions_taken = 0

for itr in range(num_games):
    env.reset()
    state, end, _ = env.observe()

    opponent_player.player, learning_player = learning_player, opponent_player.player

    if opponent_player.player == 'X':
        opponent_move = opponent_player.act(state)
        state, end, _ = env.step(opponent_move)

    while not end:
        move = policy.act(state)
        valid_move = env.check_valid(move)
        
        if valid_move:
          next_state, end, _ = env.step(move)

        if valid_move and (not end) and (env.current_player == opponent_player.player):
          opponent_move = opponent_player.act(next_state)
          next_state, end, _ = env.step(opponent_move)
          reward = env.reward(player=learning_player)
          buffer.push(state, move, next_state, reward)
        elif valid_move and end:
          reward = env.reward(player=learning_player)
          buffer.push(state, move, None, reward)        
        elif not valid_move:
          end = True
          reward = -1
          n_unavilable_actions_taken += 1
          buffer.push(state, move, None, reward)
          break
        else:
          raise ValueError("invalid move")

        loss = optimize_model(Q1, Q2, buffer, optimizer)
        
        if loss is not None:
          losses.append(loss)
        
        state = next_state.copy()

    rewards.append(reward)
    
    if len(rewards) >= LOG_EVERY:
        writer.add_scalar("Average Reward", np.mean(rewards), itr)
        writer.add_scalar("Average Loss", np.mean(loss), itr)
        writer.add_scalar("Number of unavilable actions taken", n_unavilable_actions_taken, itr)
        writer.flush()
        rewards = []
        losses = []
        n_unavilable_actions_taken = 0

    if (itr) % UPDATE_EVERY == 0:
      Q2.load_state_dict(Q1.state_dict())      
    num_trained_games += 1
    env.reset()
writer.flush()

In [ ]:
%tensorboard --logdir=runs

## Debug Code:


In [ ]:
model1 = DQN()
model2 = DQN()

In [ ]:
state1 = np.array([0, 0, 1, 0, -1, -1, 0, 0, 0]).reshape((3, 3))
state2 = np.array([0, 1, 1, 0, 1, -1, -1, 0, -1]).reshape((3, 3))
batch_size = 7
buffer = ReplayBuffer(1000, batch_size)
state1 = state_to_tensor(state1)
state2 = state_to_tensor(state2)
action1 = model1(state1).max(1).indices
action2 = model1(state2).max(1).indices
for i in range(100):
  if i % 3 == 0:
    buffer.push(state, action1, state2, torch.tensor([1], device=device))
  elif i % 3 == 1:
    buffer.push(state2, action2, state1, torch.tensor([1], device=device))
  elif i % 3 == 2:
    buffer.push(state2, action2, None, torch.tensor([1], device=device))

In [ ]:
transitions = buffer.get_batch()
batch = Transition(*zip(*transitions))

In [ ]:
model1(state).max(1).indices

tensor([6], device='cuda:0')

In [ ]:
transitions = buffer.get_batch()
batch = Transition(*zip(*transitions))
state_batch = torch.stack(batch.state)
action_batch = torch.cat(batch.action)
reward_batch = torch.cat(batch.reward)
non_final_mask = torch.tensor(tuple(map(lambda s: s is not None,
                                      batch.next_state)), device=device, dtype=torch.bool)
non_final_next_states = torch.stack([s for s in batch.next_state
                                            if s is not None])
state_action_values = model1(state_batch).take(action_batch)
next_state_values = torch.zeros(action_batch.size()[0], device=device)
next_state_values[non_final_mask] = Q2(non_final_next_states).max(1).values.detach()

In [ ]:
non_final_next_states = state_batch[non_final_mask]
non_final_next_states.size()

torch.Size([5, 3, 3, 2])

In [ ]:
state_batch.size(), \
action_batch.size(), \
reward_batch.size(), \
model1(state_batch).max(1).indices.size(), \
action_batch.size(), \
non_final_mask.size(), \
non_final_next_states.size(), \
state_action_values.size(), \
next_state_values.size(),

(torch.Size([7, 3, 3, 2]),
 torch.Size([7]),
 torch.Size([7]),
 torch.Size([7]),
 torch.Size([7]),
 torch.Size([7]),
 torch.Size([5, 3, 3, 2]),
 torch.Size([7]),
 torch.Size([7]))

In [ ]:
  model1(state_batch), action_batch, state_action_values

(tensor([[ 0.0286,  0.0695,  0.1031, -0.1010,  0.0176, -0.1728,  0.1158, -0.1029,
           0.0879],
         [ 0.0200,  0.1495,  0.1172, -0.1278,  0.0041, -0.2172,  0.0348, -0.2061,
           0.0445],
         [ 0.0200,  0.1495,  0.1172, -0.1278,  0.0041, -0.2172,  0.0348, -0.2061,
           0.0445],
         [ 0.0286,  0.0695,  0.1031, -0.1010,  0.0176, -0.1728,  0.1158, -0.1029,
           0.0879],
         [ 0.0286,  0.0695,  0.1031, -0.1010,  0.0176, -0.1728,  0.1158, -0.1029,
           0.0879],
         [ 0.0200,  0.1495,  0.1172, -0.1278,  0.0041, -0.2172,  0.0348, -0.2061,
           0.0445],
         [ 0.0286,  0.0695,  0.1031, -0.1010,  0.0176, -0.1728,  0.1158, -0.1029,
           0.0879]], device='cuda:0', grad_fn=<AddmmBackward0>),
 tensor([6, 1, 1, 6, 6, 1, 6], device='cuda:0'),
 tensor([0.1158, 0.0695, 0.0695, 0.1158, 0.1158, 0.0695, 0.1158],
        device='cuda:0', grad_fn=<TakeBackward0>))

In [ ]:
expected_state_action_values = (next_state_values * GAMMA) + reward_batch
expected_state_action_values

tensor([-5.3578,  1.0000, -5.3856, -5.3578, -5.3578,  1.0000, -5.3578],
       device='cuda:0')

In [ ]:
state_action_values

tensor([0.1495, 0.0348, 0.0348, 0.0348, 0.1495, 0.1495, 0.1495],
       device='cuda:0', grad_fn=<TakeBackward0>)

In [ ]:
state_action_values.size(), expected_state_action_values.size()

(torch.Size([7]), torch.Size([7]))

In [ ]:
# Compute Huber loss
criterion = nn.SmoothL1Loss()
loss = criterion(state_action_values, expected_state_action_values)
loss

tensor(3.6736, device='cuda:0', grad_fn=<SmoothL1LossBackward0>)

In [ ]:
type(loss.item())

float

In [ ]:
state1 = np.array([1, 1, 1, 1, 1, 1, 0, 0, 0]).reshape((3, 3))
Q1(state_to_tensor(state1)), policy.act(state1)

(tensor([[-0.9851, -0.9883, -1.0014, -1.0223, -0.9901, -1.0177, -0.9982, -1.0083,
          -0.9892]], device='cuda:0', grad_fn=<AddmmBackward0>), 0)